module.exports = {
  uri: 'https://diverseeducation.native-x.parameter1.com',
  placements: {
    'ccnews-now': {
      sponsor: '',
      'rotation-a': '',
      'rotation-b': '',
      'rotation-c': '',
      'rotation-d': '',
      'rotation-e': '',
      'reatured-resources': '',
    },
    'diverse-daily': {
      sponsor: '',
      'rotation-a': '',
      'rotation-b': '',
      'rotation-c': '',
      'rotation-d': '',
      'rotation-e': '',
      'reatured-resources': '',
    },
    'diverse-health': {
      sponsor: '',
      'rotation-a': '',
      'rotation-b': '',
      'rotation-c': '',
      'rotation-d': '',
      'rotation-e': '',
      'reatured-resources': '',
    },
    'diverse-hiring': {
      sponsor: '',
      'rotation-a': '',
      'rotation-b': '',
      'rotation-c': '',
      'rotation-d': '',
      'rotation-e': '',
      'reatured-resources': '',
    },
    'diverse-military': {
      sponsor: '',
      'rotation-a': '',
      'rotation-b': '',
      'rotation-c': '',
      'rotation-d': '',
      'rotation-e': '',
      'reatured-resources': '',
    },
    'diverse-weekly-recap': {
      sponsor: '',
      'rotation-a': '',
      'rotation-b': '',
      'rotation-c': '',
      'rotation-d': '',
      'rotation-e': '',
      'reatured-resources': '',
    },
  },
};
